In [14]:
import numpy as np

# 4 NumPy Basics: Arrays and Vectorized Computation

In [3]:
import numpy as np

In [9]:
my_arr = np.arange(1000000)

In [10]:
my_list = list(range(1000000))

In [15]:
%time for _ in range(10): my_arr2 = my_arr * 2 

CPU times: user 42 ms, sys: 14 ms, total: 56 ms
Wall time: 53 ms


In [17]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: user 809 ms, sys: 241 ms, total: 1.05 s
Wall time: 1.39 s


In [18]:
import numpy as np

In [19]:
data = np.random.randn(2, 3)

In [20]:
data

array([[-0.83101867, -1.12089378, -0.11873819],
       [-0.1047663 ,  0.54838378, -0.75644764]])

In [21]:
data * 10

array([[ -8.31018673, -11.20893782,  -1.18738188],
       [ -1.04766302,   5.48383779,  -7.56447641]])

In [22]:
data + data

array([[-1.66203735, -2.24178756, -0.23747638],
       [-0.2095326 ,  1.09676756, -1.51289528]])

In [23]:
data.shape

(2, 3)

In [25]:
data.dtype

dtype('float64')

In [10]:
data1 = [6,7.5,8,0,1]

In [11]:
arr1 = np.array(data1)

In [12]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [13]:
data2= [[1,2,3,4],[5,6,7,8]]

In [14]:
arr2 = np.array(data2)

arr2

In [15]:
arr2.ndim

2

In [17]:
arr2.shape

(2, 4)

In [18]:
arr1.dtype 

dtype('float64')

In [19]:
arr2.dtype

dtype('int64')

In [21]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [23]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [25]:
np.empty((2, 3, 2))

array([[[2.68156159e+154, 2.32035942e+077],
        [3.45845952e-323, 0.00000000e+000],
        [1.03977794e-312, 6.34762525e-066]],

       [[3.56540418e-057, 2.03873869e+184],
        [5.99407343e-066, 1.21017824e+161],
        [5.75645157e-066, 2.51402686e+180]]])

In [26]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [27]:
arr1 = np.array([1,2,3], dtype=np.float64)

In [28]:
arr2 = np.array([1,2,3], dtype=np.int32)

In [29]:
arr1.dtype

dtype('float64')

In [30]:
arr2.dtype

dtype('int32')

In [31]:
arr = np.array([1,2,3,4,5])

In [32]:
arr.dtype

dtype('int64')

In [33]:
float_arr= arr.astype(np.float64)

In [34]:
float_arr.dtype

dtype('float64')

In [35]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

In [36]:
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [37]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [38]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)

In [39]:
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [40]:
int_array = np.arange(10)

In [42]:
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)

In [43]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [44]:
empty_uint32 = np.empty(8, dtype='u4')

In [45]:
empty_uint32

array([         0, 1075314688,          0, 1075707904,          0,
       1075838976,          0, 1072693248], dtype=uint32)

In [47]:
arr = np.array([[1.,2.,3.],[4.,5.,6.]])

In [48]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [49]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [50]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [51]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [52]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [53]:
arr2 = np.array([[0.,4.,1.],[7.,2.,12]])

In [54]:
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [55]:
arr2 >arr

array([[False,  True, False],
       [ True, False,  True]])

In [56]:
arr = np.arange(10)

In [57]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
arr[5]

5

In [59]:
arr[5:8]

array([5, 6, 7])

In [60]:
arr[5:8]=12

In [61]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [62]:
arr_slice = arr[5:8]

In [63]:
arr_slice

array([12, 12, 12])

In [64]:
arr_slice[1]=12345

In [65]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [66]:
arr_slice[:]=64

In [67]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [68]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [69]:
arr2d[2]

array([7, 8, 9])

In [70]:
arr2d[0][2]

3

In [71]:
arr2d[0,2]

3

In [72]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [73]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [74]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [75]:
old_values = arr3d[0].copy()

In [76]:
arr3d[0]=42

In [77]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [78]:
arr3d[0]=old_values

In [79]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [80]:
arr3d[1,0]

array([7, 8, 9])

In [81]:
x = arr3d[1]

In [82]:
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [83]:
x[0]

array([7, 8, 9])

In [84]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [85]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [86]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [87]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [88]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [89]:
arr2d[1, :2]

array([4, 5])

In [90]:
arr2d[:2, 2]

array([3, 6])

In [91]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [93]:
arr2d[:2, 1:]=0

In [94]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [95]:
names = np.array(['Bob','Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [96]:
data = np.random.randn(7, 4)

In [97]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [98]:
data

array([[-0.27211107,  0.03835363,  0.9563044 , -0.28504263],
       [-0.80135184,  0.4940588 ,  0.79218351,  0.59876238],
       [ 0.35031905,  0.4139001 , -0.41730943, -1.34166037],
       [ 1.49049347, -0.7023194 , -0.13670665,  0.22503556],
       [ 0.79919308, -0.44348574,  0.24048695,  0.24548736],
       [ 1.24483778,  0.37785113,  0.72195934, -0.62413438],
       [ 1.12100639, -0.88541017,  0.40993996,  0.31687517]])

In [99]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [100]:
data[names == 'Bob']

array([[-0.27211107,  0.03835363,  0.9563044 , -0.28504263],
       [ 1.49049347, -0.7023194 , -0.13670665,  0.22503556]])

In [101]:
data[names == 'Bob', 2:]

array([[ 0.9563044 , -0.28504263],
       [-0.13670665,  0.22503556]])

In [102]:
data[names == 'Bob', 3]

array([-0.28504263,  0.22503556])

In [103]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [104]:
data[~(names == 'Bob')]

array([[-0.80135184,  0.4940588 ,  0.79218351,  0.59876238],
       [ 0.35031905,  0.4139001 , -0.41730943, -1.34166037],
       [ 0.79919308, -0.44348574,  0.24048695,  0.24548736],
       [ 1.24483778,  0.37785113,  0.72195934, -0.62413438],
       [ 1.12100639, -0.88541017,  0.40993996,  0.31687517]])

In [105]:
cond = names == 'Bob'

In [106]:
data[~cond]

array([[-0.80135184,  0.4940588 ,  0.79218351,  0.59876238],
       [ 0.35031905,  0.4139001 , -0.41730943, -1.34166037],
       [ 0.79919308, -0.44348574,  0.24048695,  0.24548736],
       [ 1.24483778,  0.37785113,  0.72195934, -0.62413438],
       [ 1.12100639, -0.88541017,  0.40993996,  0.31687517]])

In [107]:
mask = (names == 'Bob') | (names == 'Will')

In [108]:
mask

array([ True, False,  True,  True,  True, False, False])

In [109]:
data[mask]

array([[-0.27211107,  0.03835363,  0.9563044 , -0.28504263],
       [ 0.35031905,  0.4139001 , -0.41730943, -1.34166037],
       [ 1.49049347, -0.7023194 , -0.13670665,  0.22503556],
       [ 0.79919308, -0.44348574,  0.24048695,  0.24548736]])

In [110]:
data[data <0] = 0

In [111]:
data

array([[0.        , 0.03835363, 0.9563044 , 0.        ],
       [0.        , 0.4940588 , 0.79218351, 0.59876238],
       [0.35031905, 0.4139001 , 0.        , 0.        ],
       [1.49049347, 0.        , 0.        , 0.22503556],
       [0.79919308, 0.        , 0.24048695, 0.24548736],
       [1.24483778, 0.37785113, 0.72195934, 0.        ],
       [1.12100639, 0.        , 0.40993996, 0.31687517]])

In [112]:
data[names != 'Joe']=7

In [113]:
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.4940588 , 0.79218351, 0.59876238],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [1.24483778, 0.37785113, 0.72195934, 0.        ],
       [1.12100639, 0.        , 0.40993996, 0.31687517]])

In [114]:
arr = np.empty((8 , 4))

In [115]:
for i in range(8):
    arr[i]= i

In [116]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [117]:
arr[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [118]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [120]:
arr = np.arange(32).reshape((8, 4))

In [121]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [122]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [123]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [124]:
arr = np.arange(15).reshape((3, 5))

In [125]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [126]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [128]:
arr = np.random.randn(6, 3)

In [129]:
arr

array([[ 3.68889510e-01, -2.43348200e-02,  1.06048301e+00],
       [-1.10578028e+00, -8.00736203e-01, -1.78894742e-01],
       [-7.14421572e-02,  1.84717675e+00,  3.33035469e-02],
       [-9.31946126e-01,  1.80968758e-01,  1.32515425e+00],
       [ 1.80176805e-04,  1.77776040e+00,  3.78898451e-01],
       [ 9.53641408e-01, -2.43677964e+00, -4.93088548e-01]])

In [130]:
np.dot(arr.T, arr)

array([[ 3.14188903, -1.74765164, -1.1184937 ],
       [-1.74765164, 13.18490934,  2.29390869],
       [-1.1184937 ,  2.29390869,  3.30047083]])

In [131]:
arr = np.arange(16).reshape((2,2, 4))

In [132]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [133]:
arr.transpose((1,0, 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [134]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [135]:
arr.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

In [136]:
arr = np.arange(10)

In [137]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [138]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [139]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [140]:
x = np.random.randn(8)

In [141]:
y= np.random.randn(8)

In [142]:
x

array([ 0.09345646, -0.01044167, -0.34199967,  0.47108478,  0.0394721 ,
        1.0011984 , -0.89244537, -0.06050411])

In [143]:
y

array([ 0.16244115, -0.84518663, -0.73802468,  0.02600741,  0.70759023,
        0.64368102, -1.25117566, -0.76491035])

In [144]:
np.maximum(x,y)

array([ 0.16244115, -0.01044167, -0.34199967,  0.47108478,  0.70759023,
        1.0011984 , -0.89244537, -0.06050411])

In [145]:
arr = np.random.randn(7)* 5

In [146]:
arr

array([-1.94279306,  6.43367313,  0.95272948,  0.24383306,  4.18602968,
       15.44592019,  8.24556891])

In [147]:
remainder, whole_part = np.modf(arr)

In [148]:
remainder

array([-0.94279306,  0.43367313,  0.95272948,  0.24383306,  0.18602968,
        0.44592019,  0.24556891])

In [154]:
whole_part

array([-1.,  6.,  0.,  0.,  4., 15.,  8.])

In [155]:
arr

array([-1.94279306,  6.43367313,  0.95272948,  0.24383306,  4.18602968,
       15.44592019,  8.24556891])

In [156]:
np.sqrt(arr)

/var/folders/1s/yqryqhms0kz8vy_c_806zj7w0000gp/T/ipykernel_2422/2296558006.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr)


array([       nan, 2.53646863, 0.97607863, 0.49379456, 2.04597891,
       3.93012979, 2.87150987])

In [157]:
 np.sqrt(arr, arr)

/var/folders/1s/yqryqhms0kz8vy_c_806zj7w0000gp/T/ipykernel_2422/2830755916.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr, arr)


array([       nan, 2.53646863, 0.97607863, 0.49379456, 2.04597891,
       3.93012979, 2.87150987])

In [158]:
arr

array([       nan, 2.53646863, 0.97607863, 0.49379456, 2.04597891,
       3.93012979, 2.87150987])