In [14]:
import numpy as np

# 4 NumPy Basics: Arrays and Vectorized Computation

In [16]:
import numpy as np

In [9]:
my_arr = np.arange(1000000)

In [10]:
my_list = list(range(1000000))

In [15]:
%time for _ in range(10): my_arr2 = my_arr * 2 

CPU times: user 42 ms, sys: 14 ms, total: 56 ms
Wall time: 53 ms


In [17]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: user 809 ms, sys: 241 ms, total: 1.05 s
Wall time: 1.39 s


In [18]:
import numpy as np

In [19]:
data = np.random.randn(2, 3)

In [20]:
data

array([[-0.83101867, -1.12089378, -0.11873819],
       [-0.1047663 ,  0.54838378, -0.75644764]])

In [21]:
data * 10

array([[ -8.31018673, -11.20893782,  -1.18738188],
       [ -1.04766302,   5.48383779,  -7.56447641]])

In [22]:
data + data

array([[-1.66203735, -2.24178756, -0.23747638],
       [-0.2095326 ,  1.09676756, -1.51289528]])

In [23]:
data.shape

(2, 3)

In [25]:
data.dtype

dtype('float64')