In [14]:
import numpy as np

# 4 NumPy Basics: Arrays and Vectorized Computation

In [3]:
import numpy as np

In [9]:
my_arr = np.arange(1000000)

In [10]:
my_list = list(range(1000000))

In [15]:
%time for _ in range(10): my_arr2 = my_arr * 2 

CPU times: user 42 ms, sys: 14 ms, total: 56 ms
Wall time: 53 ms


In [17]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: user 809 ms, sys: 241 ms, total: 1.05 s
Wall time: 1.39 s


In [18]:
import numpy as np

In [19]:
data = np.random.randn(2, 3)

In [20]:
data

array([[-0.83101867, -1.12089378, -0.11873819],
       [-0.1047663 ,  0.54838378, -0.75644764]])

In [21]:
data * 10

array([[ -8.31018673, -11.20893782,  -1.18738188],
       [ -1.04766302,   5.48383779,  -7.56447641]])

In [22]:
data + data

array([[-1.66203735, -2.24178756, -0.23747638],
       [-0.2095326 ,  1.09676756, -1.51289528]])

In [23]:
data.shape

(2, 3)

In [25]:
data.dtype

dtype('float64')

In [10]:
data1 = [6,7.5,8,0,1]

In [11]:
arr1 = np.array(data1)

In [12]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [13]:
data2= [[1,2,3,4],[5,6,7,8]]

In [14]:
arr2 = np.array(data2)

arr2

In [15]:
arr2.ndim

2

In [17]:
arr2.shape

(2, 4)

In [18]:
arr1.dtype 

dtype('float64')

In [19]:
arr2.dtype

dtype('int64')

In [21]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [23]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [25]:
np.empty((2, 3, 2))

array([[[2.68156159e+154, 2.32035942e+077],
        [3.45845952e-323, 0.00000000e+000],
        [1.03977794e-312, 6.34762525e-066]],

       [[3.56540418e-057, 2.03873869e+184],
        [5.99407343e-066, 1.21017824e+161],
        [5.75645157e-066, 2.51402686e+180]]])

In [26]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [27]:
arr1 = np.array([1,2,3], dtype=np.float64)

In [28]:
arr2 = np.array([1,2,3], dtype=np.int32)

In [29]:
arr1.dtype

dtype('float64')

In [30]:
arr2.dtype

dtype('int32')

In [31]:
arr = np.array([1,2,3,4,5])

In [32]:
arr.dtype

dtype('int64')

In [33]:
float_arr= arr.astype(np.float64)

In [34]:
float_arr.dtype

dtype('float64')

In [35]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

In [36]:
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [37]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [38]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)

In [39]:
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [40]:
int_array = np.arange(10)

In [42]:
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)

In [43]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [44]:
empty_uint32 = np.empty(8, dtype='u4')

In [45]:
empty_uint32

array([         0, 1075314688,          0, 1075707904,          0,
       1075838976,          0, 1072693248], dtype=uint32)

In [47]:
arr = np.array([[1.,2.,3.],[4.,5.,6.]])

In [48]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [49]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [50]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [51]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [52]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [ ]:
arr2 = np.array([[0.,4.,1.],[7.,2.,12]])